dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"
dotenv: .env
networks:
  rinkeby:
    eth_usd_price_feed: "0x7bD115974BEF92Ab5E1Ee6ac67A20d7bF2be409E"
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
